### PR TITLE
added linux mint support

### PR DESCRIPTION
**Pull request by mhristof**

### CODE REVIEW

**Comment by steenzout** [comment]
@mhristof it seems you are using `codename` and it breaks tests for ansible 2.2:

```
TASK [oracle-java : debian | (ubuntu or mint) | add java ppa repo] *************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: codename"}
	to retry, use: --limit @/home/travis/build/ansiblebit/oracle-java/tests/test.retry
```

https://travis-ci.org/ansiblebit/oracle-java/jobs/314874152

**Comment by mhristof** [comment]
whoops, completely missed older version support.
I dont think there is any non-hacky way to get this to work in 2.2, so i guess ill create a new PR and revert this merge ?

**Comment by steenzout** [comment]
no need to do a `revert` :)
I merged it with `develop` branch instead of `master`.
if you want you can create a new PR and maybe split `debian.yml` and use a `debian_ubuntu.yml` and `debian_mint.yml` calls even though they may have mostly the same tasks?

if not, I'll have at time whenever I have time.
do you know of any vagrant boxes for Mint you would recommend?

**Comment by mhristof** [comment]
ill can do the split, no worries (just to be clear, mint will require ansible 2.3 but all the others will be OK at ansible 2.2, right ?)

RE vagrant and mint, im using i've started using `ajxb/mint-18.3` and it seems OK. Is the vagrant testing somewhere else ? I couldnt see anything in `.travis.yml`

**Comment by steenzout** [comment]
you can make `ansible 2.3` as a requirements to run the `mint.yml` tasks.
you can put that validation on the `validation.yml`.

**Comment by steenzout** [comment]
you'll need to add the vagrant box to the `tests/boxes.yml` file.
to run the vagrant tests you can use `tox -e py27-ansible23 -- --box <mint>.vagrant.dev`.
you can also use the `vagrant.sh` bash script and pass a `--box` parameter by hand but the above is safer since it will use a `virtualenv`.

**Comment by steenzout** [comment]
travis-ci only runs tests against `ubuntu/trusty`.

**Pull request merged**
