### PR TITLE
Improved ansible code, removed dependency

### PR DESCRIPTION
**Pull request by hryamzik**
- replaced shell with modules
- replaced fail-based checks with changing based ones
- removed launchpad-ppa-webupd8 dependency – looks too complicated for such a simple role
- cleaned up README
- changed defaults to set java as default – I do hate changing default behaviour but hey, you expect role to install java in a useful way when applying role with no arguments!

### CODE REVIEW

**Comment by steenzout** [comment]
@hryamzik this is failing on travis:

```
TASK [oracle-java : Set license as accepted] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "debconf: DbDriver \"passwords\" warning: could not open /var/cache/debconf/passwords.dat: Permission denied\ndebconf: DbDriver \"config\": could not write /var/cache/debconf/config.dat-new: Permission denied\n"}
```

I'll test this on the vagrant boxes but it would be good if you could have a look.

usage of `block` makes the Ansible requirements be >= 2.x so the travis-ci tests should fail for 1.9 (and that's ok, I can update that part).

**Comment by hryamzik** [comment]
Tests do not set `become: yes` on host level, what's the reason for that?

Ansible 2.x is out there for a while and brings us a lot of good stuff. Why support 1.9?

**Comment by steenzout** [comment]
it's ok to drop ansible 1.9 support but there are several files that need to be updated.

I've fixed the other minor issues.

I never run a playbook with `become: yes`.
It has been some time but the `${USER}` env variable might get set to something I don't want.
Maybe this ain't a problem for a test playbook and not for this role in particular but just to be safe I add `become: yes` for all tasks that really need `root/sudo` privileges.
I've fixed this as well.

**Comment by steenzout** [comment]
continued on #33 ...

**Comment by steenzout** [comment]
https://github.com/ansiblebit/oracle-java/releases/tag/5.14.0

**Comment by hryamzik** [comment]
Thanks!

**Pull request closed without merging**
